db:
  image: mysql:5.7
  ports:
    - "3308:3306"
  volumes:
    - /var/lib/mysql:/var/lib/mysql
  environment:
    - MYSQL_DATABASE=homestead
    - MYSQL_USER=homestead
    - MYSQL_PASSWORD=secret
    - MYSQL_ROOT_PASSWORD=root
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db:mysql
  ports:
    - 8282:80
  environment:
    - PMA_HOST=mysql
    - PMA_USER=root
    - PMA_PASSWORD=root
    - MYSQL_USER=homestead
    - MYSQL_PASSWORD=secret
    - MYSQL_ROOT_PASSWOR=root
  restart: always
client:
    build: ./
    ports:
      - "3000:3000"
      - "9856:9856"
    links:
    - db
    stdin_open: true
    volumes:
       - ./:/home/app/
       - /home/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true