db:
  image: mysql:5.7
  ports:
    - "3308:3306"
  volumes:
    - /var/lib/mysql:/var/lib/mysql
  environment:
    - MYSQL_DATABASE=homestead
    - MYSQL_USER=homestead
    - MYSQL_PASSWORD=secret
    - MYSQL_ROOT_PASSWORD=root
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db:mysql
  ports:
    - 8282:80
  environment:
    - PMA_HOST=mysql
    - PMA_USER=root
    - PMA_PASSWORD=root
    - MYSQL_USER=homestead
    - MYSQL_PASSWORD=secret
    - MYSQL_ROOT_PASSWOR=root
  restart: always
nodejs:
  build: ./api
  volumes:
      - ./api:/home/app/
      - /home/app/node_modules
  links:
    - db
  ports:
    - 5000:5000